### ISSUE TITLE
search console 導入

### ISSUE THREAD

**Issue by space-satoshi** [Space-inc/space-english#71]
https://search.google.com/u/1/search-console/welcome

space.ink.future@gmail.com
上記のアカウントで連携して欲しい。

おそらくheadに入れるだけ！
その後、アナリティクスと繋げれる見たい。

▼参考記事
https://ferret-plus.com/11552

**Comment by RintaroTawara** [comment]
@space-satoshi 
行けやした
[![Image from Gyazo](https://i.gyazo.com/94dd1ad58d988ccccf28ddad14548215.png)](https://gyazo.com/94dd1ad58d988ccccf28ddad14548215)
